site_name: Easys
docs_dir: 'documents'
use_directory_urls: false
theme:
  name: material
  palette:
    primary: light blue
  icon:
    repo: fontawesome/brands/github
    logo: material/robot

plugins:
  - search:
  - i18n:
      default_language: en
      languages:
        en: English
        ja: 日本語
      nav_translations:
        ja:
          Easys_ros: いしすろす
          Manufacturing instructions: 組み立て手順書

# github icon
repo_url: https://github.com/tamago117/Easys_ros
repo_name: tamago117/Easys_ros

extra:
  generator: false
